G = { 
    'nodes': [
       {'id': 'New York', 'pos': [-2.71087761, 6.13420722]},
       {'id': 'Los Angeles', 'pos': [-2.86191672, 0.46045476]},
       {'id': 'Tucson', 'pos': [3.52255683,6.67295887]},
       {'id': 'Chicago', 'pos': [3.50940235,0.02318137]},
       {'id': 'Dallas', 'pos': [3.613491  ,0.19864336]},
       {'id': 'Mexico City', 'pos': [-2.45880189, 0.32227176]},
       {'id': 'Toronto', 'pos': [6.64718034,3.2308766 ]},
       {'id': 'Seattle', 'pos': [0.05142835,2.80363175]},
       {'id': 'Paris', 'pos': [ 2.94222335,-0.91742763]},
       {'id': 'London', 'pos': [ 2.95444885,-0.86363797]},
       {'id': 'Rome', 'pos': [ 2.77366592,-1.06559451]},
       {'id': 'Berlin', 'pos': [ 9.00997632,-0.88036663]},
       {'id': 'Oslo', 'pos': [ 5.88970813,-2.39301945]},
       {'id': 'Moscow', 'pos': [-3.89296382,-7.04808796]},
       {'id': 'Reykjavik', 'pos': [ 3.0138665 ,-0.56759567]},
       {'id': 'New Delhi', 'pos': [ 7.84756442,-0.53029119]},
       {'id': 'Beijing', 'pos': [-1.31165605,-9.43187752]},
       {'id': 'Jakarta', 'pos': [4.15656673,3.08784947]},
       {'id': 'Tokyo', 'pos': [8.17699581,6.61242411]},
       {'id': 'Sydney', 'pos': [ 0.49107373,-5.5074014 ]},
       {'id': 'Auckland', 'pos': [0.13518873,1.02599898]},
       {'id': 'Rio de Janeiro', 'pos': [14.25295568,-9.04185742]},
       {'id': 'Sao Paulo', 'pos': [1.67242298,9.75268299]},
       {'id': 'Bogota', 'pos': [ 4.19432137,-0.02184669]},
       {'id': 'Lima', 'pos': [4.46986399,0.09503286]},
       {'id': 'Buenos Aires', 'pos': [-4.49536205, 3.23064856]},
       {'id': 'Cape Town', 'pos': [2.76019525,3.88086107]},
       {'id': 'Nairobi', 'pos': [ 6.83641053,11.44915142]},
       {'id': 'Cairo', 'pos': [ 2.02076065,-1.17896741]},
       {'id': 'Dakar', 'pos': [4.14444968,5.27160028]},
       {'id': 'Lisbon', 'pos': [6.46393855,4.12506609]},
       {'id': 'Madrid', 'pos': [ 9.4698471 ,-1.01021096]}
     ],
    'edges': [
       {'source': 'New York', 'target': 'Toronto'},
       {'source': 'New York', 'target': 'Chicago'},
       {'source': 'New York', 'target': 'Dallas'},
       {'source': 'New York', 'target': 'Mexico City'},
       {'source': 'New York', 'target': 'Tucson'},
       {'source': 'Los Angeles', 'target': 'Tucson'},
       {'source': 'Los Angeles', 'target': 'Seattle'},
       {'source': 'Los Angeles', 'target': 'Dallas'},
       {'source': 'Los Angeles', 'target': 'Mexico City'},
       {'source': 'Los Angeles', 'target': 'Chicago'},
       {'source': 'Tucson', 'target': 'Los Angeles'},
       {'source': 'Tucson', 'target': 'Dallas'},
       {'source': 'Tucson', 'target': 'Mexico City'},
       {'source': 'Tucson', 'target': 'Seattle'},
       {'source': 'Tucson', 'target': 'Chicago'},
       {'source': 'Chicago', 'target': 'Toronto'},
       {'source': 'Chicago', 'target': 'New York'},
       {'source': 'Chicago', 'target': 'Dallas'},
       {'source': 'Chicago', 'target': 'Tucson'},
       {'source': 'Chicago', 'target': 'Mexico City'},
       {'source': 'Dallas', 'target': 'Chicago'},
       {'source': 'Dallas', 'target': 'Tucson'},
       {'source': 'Dallas', 'target': 'Mexico City'},
       {'source': 'Dallas', 'target': 'Toronto'},
       {'source': 'Dallas', 'target': 'Los Angeles'},
       {'source': 'Mexico City', 'target': 'Dallas'},
       {'source': 'Mexico City', 'target': 'Tucson'},
       {'source': 'Mexico City', 'target': 'Los Angeles'},
       {'source': 'Mexico City', 'target': 'Chicago'},
       {'source': 'Mexico City', 'target': 'Bogota'},
       {'source': 'Toronto', 'target': 'New York'},
       {'source': 'Toronto', 'target': 'Chicago'},
       {'source': 'Toronto', 'target': 'Dallas'},
       {'source': 'Toronto', 'target': 'Tucson'},
       {'source': 'Toronto', 'target': 'Mexico City'},
       {'source': 'Seattle', 'target': 'Los Angeles'},
       {'source': 'Seattle', 'target': 'Tucson'},
       {'source': 'Seattle', 'target': 'Dallas'},
       {'source': 'Seattle', 'target': 'Chicago'},
       {'source': 'Seattle', 'target': 'Toronto'},
       {'source': 'Paris', 'target': 'London'},
       {'source': 'Paris', 'target': 'Berlin'},
       {'source': 'Paris', 'target': 'Madrid'},
       {'source': 'Paris', 'target': 'Rome'},
       {'source': 'Paris', 'target': 'Oslo'},
       {'source': 'London', 'target': 'Paris'},
       {'source': 'London', 'target': 'Berlin'},
       {'source': 'London', 'target': 'Oslo'},
       {'source': 'London', 'target': 'Madrid'},
       {'source': 'London', 'target': 'Rome'},
       {'source': 'Rome', 'target': 'Paris'},
       {'source': 'Rome', 'target': 'Berlin'},
       {'source': 'Rome', 'target': 'Madrid'},
       {'source': 'Rome', 'target': 'London'},
       {'source': 'Rome', 'target': 'Lisbon'},
       {'source': 'Berlin', 'target': 'Oslo'},
       {'source': 'Berlin', 'target': 'Paris'},
       {'source': 'Berlin', 'target': 'London'},
       {'source': 'Berlin', 'target': 'Rome'},
       {'source': 'Berlin', 'target': 'Moscow'},
       {'source': 'Oslo', 'target': 'Berlin'},
       {'source': 'Oslo', 'target': 'London'},
       {'source': 'Oslo', 'target': 'Paris'},
       {'source': 'Oslo', 'target': 'Moscow'},
       {'source': 'Oslo', 'target': 'Reykjavik'},
       {'source': 'Moscow', 'target': 'Berlin'},
       {'source': 'Moscow', 'target': 'Oslo'},
       {'source': 'Moscow', 'target': 'Rome'},
       {'source': 'Moscow', 'target': 'Paris'},
       {'source': 'Moscow', 'target': 'London'},
       {'source': 'Reykjavik', 'target': 'Oslo'},
       {'source': 'Reykjavik', 'target': 'London'},
       {'source': 'Reykjavik', 'target': 'Paris'},
       {'source': 'Reykjavik', 'target': 'Berlin'},
       {'source': 'Reykjavik', 'target': 'Madrid'},
       {'source': 'New Delhi', 'target': 'Beijing'},
       {'source': 'New Delhi', 'target': 'Moscow'},
       {'source': 'New Delhi', 'target': 'Cairo'},
       {'source': 'New Delhi', 'target': 'Jakarta'},
       {'source': 'New Delhi', 'target': 'Nairobi'},
       {'source': 'Beijing', 'target': 'Tokyo'},
       {'source': 'Beijing', 'target': 'New Delhi'},
       {'source': 'Beijing', 'target': 'Jakarta'},
       {'source': 'Beijing', 'target': 'Moscow'},
       {'source': 'Beijing', 'target': 'Oslo'},
       {'source': 'Jakarta', 'target': 'New Delhi'},
       {'source': 'Jakarta', 'target': 'Beijing'},
       {'source': 'Jakarta', 'target': 'Sydney'},
       {'source': 'Jakarta', 'target': 'Tokyo'},
       {'source': 'Jakarta', 'target': 'Auckland'},
       {'source': 'Tokyo', 'target': 'Beijing'},
       {'source': 'Tokyo', 'target': 'Jakarta'},
       {'source': 'Tokyo', 'target': 'New Delhi'},
       {'source': 'Tokyo', 'target': 'Moscow'},
       {'source': 'Tokyo', 'target': 'Seattle'},
       {'source': 'Sydney', 'target': 'Auckland'},
       {'source': 'Sydney', 'target': 'Jakarta'},
       {'source': 'Sydney', 'target': 'Tokyo'},
       {'source': 'Sydney', 'target': 'Beijing'},
       {'source': 'Sydney', 'target': 'New Delhi'},
       {'source': 'Auckland', 'target': 'Sydney'},
       {'source': 'Auckland', 'target': 'Jakarta'},
       {'source': 'Auckland', 'target': 'Tokyo'},
       {'source': 'Auckland', 'target': 'Buenos Aires'},
       {'source': 'Auckland', 'target': 'Beijing'},
       {'source': 'Rio de Janeiro', 'target': 'Sao Paulo'},
       {'source': 'Rio de Janeiro', 'target': 'Buenos Aires'},
       {'source': 'Rio de Janeiro', 'target': 'Lima'},
       {'source': 'Rio de Janeiro', 'target': 'Bogota'},
       {'source': 'Rio de Janeiro', 'target': 'Dakar'},
       {'source': 'Sao Paulo', 'target': 'Rio de Janeiro'},
       {'source': 'Sao Paulo', 'target': 'Buenos Aires'},
       {'source': 'Sao Paulo', 'target': 'Lima'},
       {'source': 'Sao Paulo', 'target': 'Bogota'},
       {'source': 'Sao Paulo', 'target': 'Dakar'},
       {'source': 'Bogota', 'target': 'Lima'},
       {'source': 'Bogota', 'target': 'Mexico City'},
       {'source': 'Bogota', 'target': 'Dallas'},
       {'source': 'Bogota', 'target': 'New York'},
       {'source': 'Bogota', 'target': 'Sao Paulo'},
       {'source': 'Lima', 'target': 'Bogota'},
       {'source': 'Lima', 'target': 'Buenos Aires'},
       {'source': 'Lima', 'target': 'Sao Paulo'},
       {'source': 'Lima', 'target': 'Rio de Janeiro'},
       {'source': 'Lima', 'target': 'Mexico City'},
       {'source': 'Buenos Aires', 'target': 'Sao Paulo'},
       {'source': 'Buenos Aires', 'target': 'Rio de Janeiro'},
       {'source': 'Buenos Aires', 'target': 'Lima'},
       {'source': 'Buenos Aires', 'target': 'Bogota'},
       {'source': 'Buenos Aires', 'target': 'Cape Town'},
       {'source': 'Cape Town', 'target': 'Nairobi'},
       {'source': 'Cape Town', 'target': 'Rio de Janeiro'},
       {'source': 'Cape Town', 'target': 'Sao Paulo'},
       {'source': 'Cape Town', 'target': 'Dakar'},
       {'source': 'Cape Town', 'target': 'Buenos Aires'},
       {'source': 'Nairobi', 'target': 'Cairo'},
       {'source': 'Nairobi', 'target': 'Cape Town'},
       {'source': 'Nairobi', 'target': 'Rome'},
       {'source': 'Nairobi', 'target': 'New Delhi'},
       {'source': 'Nairobi', 'target': 'Madrid'},
       {'source': 'Cairo', 'target': 'Rome'},
       {'source': 'Cairo', 'target': 'Berlin'},
       {'source': 'Cairo', 'target': 'Moscow'},
       {'source': 'Cairo', 'target': 'Paris'},
       {'source': 'Cairo', 'target': 'Madrid'},
       {'source': 'Dakar', 'target': 'Lisbon'},
       {'source': 'Dakar', 'target': 'Madrid'},
       {'source': 'Dakar', 'target': 'Rome'},
       {'source': 'Dakar', 'target': 'Paris'},
       {'source': 'Dakar', 'target': 'London'},
       {'source': 'Lisbon', 'target': 'Madrid'},
       {'source': 'Lisbon', 'target': 'Paris'},
       {'source': 'Lisbon', 'target': 'London'},
       {'source': 'Lisbon', 'target': 'Rome'},
       {'source': 'Lisbon', 'target': 'Berlin'},
       {'source': 'Madrid', 'target': 'Lisbon'},
       {'source': 'Madrid', 'target': 'Paris'},
       {'source': 'Madrid', 'target': 'London'},
       {'source': 'Madrid', 'target': 'Rome'},
       {'source': 'Madrid', 'target': 'Berlin'}
     ]
}